DROP DATABASE IF EXISTS AEROPARKER;
CREATE DATABASE AEROPARKER;
USE AEROPARKER;

CREATE TABLE AP_CUSTOMERS(
ID INT AUTO_INCREMENT,
REGISTERED DATETIME NOT NULL,
EMAIL_ADDRESS VARCHAR(255) UNIQUE NOT NULL,
TITLE VARCHAR(5) NOT NULL, 
FIRST_NAME VARCHAR(50) NOT NULL,
SECOND_NAME VARCHAR(50) NOT NULL,
ADDRESS_LINE_1 VARCHAR(255) NOT NULL,
ADDRESS_LINE_2 VARCHAR(255),
CITY VARCHAR(255),
POSTCODE VARCHAR(10) NOT NULL,
TELEPHONE_NUMBER VARCHAR(20),
CONSTRAINT AP_ID_PK PRIMARY KEY(ID)
);

CREATE TABLE AP_SITES(
ID INT AUTO_INCREMENT NOT NULL, 
NAME VARCHAR(255) NOT NULL,
CONSTRAINT AP_SITES_PK PRIMARY KEY(ID)
);

CREATE TABLE AP_CUSTOMERS_SITES(
CUSTOMER_ID INT NOT NULL,
SITE_ID INT NOT NULL
);

ALTER TABLE AP_CUSTOMERS_SITES ADD CONSTRAINT AP_ID_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES AP_CUSTOMERS(ID);
ALTER TABLE AP_CUSTOMERS_SITES ADD CONSTRAINT AP_SITE_ID_FK FOREIGN KEY(SITE_ID) REFERENCES AP_SITES(ID);